# my lovely helix config
 
theme = "flexoki_dark"

[editor]
line-number = 'absolute'
soft-wrap.enable = true
color-modes = true
cursor-shape = { insert = 'bar', normal = 'block', select = 'block' }

[editor.lsp]
display-inlay-hints	= true

[editor.statusline]
left = [ 'mode', 'spinner', 'register' ]
center = [ 'file-name', 'file-modification-indicator' ]
right = [ 'position', 'separator', 'total-line-numbers', 'separator', 'position-percentage' ]

[editor.auto-save]
focus-lost = true 

[editor.inline-diagnostics]
cursor-line = 'info'
other-lines = 'error'

[keys.normal]
'C-p' = ':lsp-workspace-command'
'tab' = ':buffer-next'
'S-tab' = ':buffer-previous'
'ret' = 'goto_word'

[keys.normal.space.d]
'd' = ':buffer-close!'
'p' = 'diagnostics_picker'

[keys.normal.space]
'w' = ':write'
'q' = ':quit'
'o' = ':sh open %{buffer_name}'

[keys.insert]
j = { j = 'normal_mode', k = 'normal_mode' }
