# my lovely helix config
 
theme = "flexoki_dark"

[editor]
line-number = 'relative'
cursorline = true
soft-wrap.enable = true
color-modes = true
cursor-shape = { insert = 'bar', normal = 'block', select = 'block' }

[editor.lsp]
display-inlay-hints	= true

[editor.statusline]
left = [ 'mode', 'spinner', 'register' ]
center = [ 'file-name', 'file-modification-indicator' ]
right = [ 'position', 'separator', 'total-line-numbers', 'separator', 'position-percentage' ]

[editor.auto-save]
focus-lost = true 

[editor.inline-diagnostics]
cursor-line = 'info'
other-lines = 'error'

[keys.normal]
'tab' = ':buffer-next'
'S-tab' = ':buffer-previous'
'C-p' = ':lsp-workspace-command'
'C-r' = ':reload'
'C-y' = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]

[keys.normal.space.d]
'd' = ':buffer-close!'
'p' = 'diagnostics_picker'

[keys.normal.space]
'w' = ':write'
'q' = ':quit'
'f' = 'file_picker_in_current_directory'
'F' = 'file_picker_in_current_buffer_directory'
'e' = 'file_explorer_in_current_directory'
'E' = 'file_explorer_in_current_buffer_directory'

[keys.insert]
j = { j = 'normal_mode', k = 'normal_mode' }
